---
collections:
  - name: community.general
  - name: amazon.aws
  - name: community.aws
  - name: ansible.netcommon
  - name: community.azure
  - name: azure.azcollection
    source: https://galaxy.ansible.com
