---
# Basic provisioning example
- name: Ansible test
  hosts: localhost
  tasks:
  - name: launching AWS instance using Ansible
    amazon.aws.ec2_instance:
      key_name: testing
      instance_type: t2.micro
      image: ami-0261755bbcb8c4a84
      region: us-east-1
      wait: yes
      group: "Ansible"
      count: 1
      vpc_subnet_id: default
      assign_public_ip: yes
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
