---
- name: Create Azure Virtual Machine
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Set Azure credentials
      azure.azcollection.azure_rm_registrationdefinition:
        subscription_id: "{{ AZURE_SUBSCRIPTION_ID }}"
        client_id: "{{ AZURE_CLIENT_ID }}"
        secret: "{{ AZURE_SECRET }}"
        tenant: "{{ AZURE_TENANT }}"
      register: auth_result

    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "myResourceGroup"
        location: "East US"
        tags:
          environment: "test"
        state: present
        auth_source: "{{ auth_result }}"
      register: rg_result

    - name: Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "myResourceGroup"
        name: "myVNet"
        address_prefixes: "10.0.0.0/16"
        state: present
        auth_source: "{{ auth_result }}"
      register: vnet_result

    - name: Create subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "myResourceGroup"
        virtual_network_name: "myVNet"
        name: "mySubnet"
        address_prefix: "10.0.0.0/24"
        state: present
        auth_source: "{{ auth_result }}"
      register: subnet_result

    - name: Create public IP address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "myResourceGroup"
        allocation_method: "Dynamic"
        name: "myPublicIP"
        state: present
        auth_source: "{{ auth_result }}"
      register: public_ip_result

    - name: Create network security group
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "myResourceGroup"
        name: "myNSG"
        rules:
          - name: "SSH"
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
        state: present
        auth_source: "{{ auth_result }}"
      register: nsg_result

    - name: Create virtual machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "myResourceGroup"
        name: "myVM"
        vm_size: "Standard_DS2_v2"
        admin_username: "azureuser"
        admin_password: "155169ad-1cb0-4ba0-a40e-fafe25bef1ff"
        network_interfaces:
          - name: "nic1"
            primary: true
        os_type: "Linux"
        image:
          offer: "UbuntuServer"
          publisher: "Canonical"
          sku: "20.04-LTS"
          version: "latest"
        os_disk:
          name: "myOsDisk"
          caching: "ReadWrite"
          create_option: "FromImage"
        public_ip_name: "myPublicIP"
        tags:
          environment: "test"
        state: present
        auth_source: "{{ auth_result }}"
      register: vm_result
