---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: False
  vars:
    regions: 
      - us-east-1
      - us-east-2
    instance_type: "t2.micro"
    ami_id: "ami-0261755bbcb8c4a84"
    key_name: "testing"
    security_group: "sg-0e5c4af056257477e"
  tasks:
    - name: create EC2 Instance
      amazon.aws.ec2_instance:
        region: "{{ item }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        security_groups: "{{ security_group }}"
        wait: yes
        count: "{{ instances_per_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2_instance
      loop: "{{ regions }}"


    - name: Display EC2 Instance Information
      debug:
        var: ec2_instance.instances[0]
