---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: False
  vars:
    region: "us-east-1"
    instance_type: "t2.micro"
    ami_id: "ami-0261755bbcb8c4a84"
    key_name: "testing"
    security_group: "sg-0e5c4af056257477e"
  tasks:
    - name: create EC2 Instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        security_groups: "{{ security_group }}"
        assign_public_ip: yes
        wait: yes
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      register: ec2_instance


    - name: Display EC2 Instance Information
      debug:
        var: ec2_instance.instances[0]
