---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: False
  vars:
    region: "us-east-1"  # Change this to your desired region
    instance_type: "t2.micro"
    ami_id: "ami-0261755bbcb8c4a84"  # Replace with your desired AMI ID
    key_name: "testing"  # Replace with your EC2 key pair name
    security_group: "sg-0e5c4af056257477e"  # Replace with your security group ID
  tasks:
    - name: create EC2 Instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        security_groups: "{{ security_group }}"
        assign_public_ip: yes
        wait: yes
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2_instance


    - name: Display EC2 Instance Information
      debug:
        var: ec2_instance.instances[0]
