---
- name: Setup VPC and EC2 instances
  hosts: localhost
  gather_facts: no
  vars:
    region: "us-east-2"

  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "MyVPC11"
        state: present
        cidr_block: "10.0.0.0/16"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: vpc

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        state: present
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: vpc_igw

    - name: Create Subnets
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.az }}"
        state: present
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      loop:
        - { cidr: 10.0.1.0/24, az: us-east-1a }
        - { cidr: 10.0.2.0/24, az: us-east-1b }
        - { cidr: 10.0.3.0/24, az: us-east-1c }
      register: subnets

    - name: Create Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: "PublicRouteTable"
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ vpc_igw.gateway_id }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: route_table

    - name: Create Security Group
      amazon.aws.ec2_group:
        name: "MySecurityGroup"
        description: "Security Group for EC2 instances"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
      register: security_group

#    - name: Print VPC ID and Subnet IDs
#      debug:
#        msg: "VPC ID: {{ vpc.vpc.id }}, Subnet IDs: {{ subnets.results | map(attribute='id') | join(', ') }}"
