---
- name: Create VPC, Subnets, Internet Gateway, Route Table, and Security Group
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set AWS credentials
      set_fact:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      delegate_to: localhost

    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: MyVPC3
        cidr_block: 10.0.0.0/16
        region: us-east-1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: vpc

    - name: Create Subnets
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.az }}"
        state: present
        region: us-east-1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      loop:
        - "ap-southeast-2a"
        - "ap-southeast-2b"
        - "ap-southeast-2c"
      register: subnets

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-1
        state: present
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: igw

    - name: Create Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: route_table

    - name: Associate Subnets with Route Table
      amazon.aws.ec2_vpc_route_table:
        subnet_id: "{{ item.subnet.id }}"
        route_table_id: "{{ route_table.route_table.id }}"
        region: us-east-1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      loop: "{{ vpc.subnets }}"
      loop_control:
        loop_var: item

    - name: Create Security Group
      amazon.aws.ec2_group:
        name: MySecurityGroup
        description: Allow SSH and HTTP traffic
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
            cidr_ip: 0.0.0.0/0
      register: security_group
